# Generated by Django 2.0.2 on 2018-03-24 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=70)),
                ('degree', models.CharField(max_length=100)),
                ('cathedra', models.CharField(max_length=100)),
                ('additional_info', models.CharField(max_length=2000)),
                ('seniority', models.IntegerField(default=0)),
                ('image', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.CharField(max_length=300)),
                ('lecturer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Lecturer')),
            ],
        ),
        migrations.AddField(
            model_name='disciplines',
            name='lecturer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Lecturer'),
        ),
    ]
