# Generated by Django 2.0.2 on 2018-03-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='work',
            field=models.CharField(default='доцент', max_length=100),
        ),
    ]
