# Generated by Django 2.0.2 on 2018-03-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_lecturer_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='additional_info',
            field=models.CharField(max_length=10000),
        ),
    ]
