# Generated by Django 2.0.2 on 2018-03-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_auto_20180324_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='publication',
            field=models.CharField(max_length=900),
        ),
    ]
