# Generated by Django 2.0.2 on 2018-03-27 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_auto_20180324_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=20000)),
                ('history', models.CharField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='Science_interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('science_interest', models.CharField(max_length=800)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Department')),
            ],
        ),
        migrations.AddField(
            model_name='lecturer',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.Department'),
            preserve_default=False,
        ),
    ]
